### ISSUE TITLE
B Matrix has Problems with asymtric laminates

### ISSUE THREAD

**Issue by CPS-BTU** [rafaelpsilva07/composipy#28]
Dear Raphael, 
thanks a lot for your work on composipy. I recently started to work with it and I'm sure it takes lot of work of my shoulders regarding the clt stuff. 
Could you please check the b Matrix calulation? For asymetric laminates the calulation flips the signs. I Assume the the z coordinate migth be definess up side down?

**Comment by rafaelpsilva07** [comment]
@CPS-BTU, thank you for creating this issue! Sure, I can check it. 

Could you send to me an example of your application? I can use as test case. You can observe there is no test cases for the matrix [B] calculation, that is because I didn't have any application for it so far.

**Comment by CPS-BTU** [comment]
Hi Rafael, I'm not used to write here, so I hope I can give you the Info needed. 
See this code snippet, a simple +-45° Laminate with the same material data you used on your Youtubevideo. 
The B-Matrix has flipped signs. It should have:
![grafik](https://github.com/user-attachments/assets/370e8c60-3d35-4814-819f-9175d8227ced)
I used Elamx (https://tu-dresden.de/ing/maschinenwesen/ilr/lft/elamx2/elamx) and another self written code. 


```
from composipy import OrthotropicMaterial
from composipy import LaminateProperty

E1 = 137.9e3
E2 = 11.7e3
v12 = 0.31
G12 = 4.82e3
t = 0.1524

mat = OrthotropicMaterial(E1, E2, v12, G12, t)

stack = [45, -45]
lam=LaminateProperty(stack,mat)
lam.ABD
lam.B
#array([[   0.      ,    0.      , -738.796518],
       #[   0.      ,    0.      , -738.796518],
       #[-738.796518, -738.796518,    0.      ]])
```

**Comment by CPS-BTU** [comment]
> Hi Rafael, I'm not used to write here, so I hope I can give you the Info needed. See this code snippet, a simple +-45° Laminate with the same material data you used on your Youtubevideo. The B-Matrix has flipped signs. It should have: ![grafik](https://private-user-images.githubusercontent.com/186052585/379666554-370e8c60-3d35-4814-819f-9175d8227ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTYxMTYsIm5iZiI6MTcyOTc1NTgxNiwicGF0aCI6Ii8xODYwNTI1ODUvMzc5NjY2NTU0LTM3MGU4YzYwLTNkMzUtNDgxNC04MTlmLTkxNzVkODIyN2NlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwNzQzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWZmNWUzYmJhNzVjMWE3MGQ5NDJiNTU5ZDAyZmUwYTU4MDU5NThmMDE1YTliMzQ0ZGIyNjA3ZWZmMGUwNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w-1MhGvEFeNq-UTvC5XZyqbbg_dwcGh75Pr52_bJ0xk) I used Elamx (https://tu-dresden.de/ing/maschinenwesen/ilr/lft/elamx2/elamx) and another self written code.
> 
> ```
> from composipy import OrthotropicMaterial
> from composipy import LaminateProperty
> 
> E1 = 137.9e3
> E2 = 11.7e3
> v12 = 0.31
> G12 = 4.82e3
> t = 0.1524
> 
> mat = OrthotropicMaterial(E1, E2, v12, G12, t)
> 
> stack = [45, -45]
> lam=LaminateProperty(stack,mat)
> lam.ABD
> lam.B
> #array([[   0.      ,    0.      , -738.796518],
>        #[   0.      ,    0.      , -738.796518],
>        #[-738.796518, -738.796518,    0.      ]])
> ```
I need this for calculation of bend-strain coupling like this here: 
![grafik](https://github.com/user-attachments/assets/3e7b40be-6016-49b4-8743-82f6995b0c96)
![grafik](https://github.com/user-attachments/assets/c9ad6517-e42f-40fd-be49-52ff7c3e11aa)

**Comment by rafaelpsilva07** [comment]
@CPS-BTU, thank you for reporting this. I checked against Altair HyperLaminate. So, at the end of the day it is a matter of convention if you are starting from the top to the bottom or the other way around.
I'll think about what is the best way to approach this.

This is a really good finding anyway.

**Comment by rafaelpsilva07** [comment]
@CPS-BTU, I tested against HyperLaminate and Femap Nastran and their convention are similar to the one I am using. 
Please, refer to the image below for the Femap Nastran result.

![image](https://github.com/user-attachments/assets/cbf605b6-2bf0-41b5-9bac-3ac8b2ab50cb)

Also, refer to the image below for a Daniel and Ori Ishai reference.


![image](https://github.com/user-attachments/assets/78b8a495-07dc-4ceb-9384-3955c80f1999)

**Comment by rafaelpsilva07** [comment]
The final answer for this question is: I'll update the documentation for making this convention clear.
The first element of the list correspond to the bottom most ply and the last correspond to the top most.

**Comment by CPS-BTU** [comment]
Hi Rapheal, 
Thank you very much for this. 
I looked it up again in Schürmann (German reference book on CLT, ISBN: 978-3-540-72189-5). The B and D matrix depend on the choice of reference layer, as not only the thickness of the individual layer but also the position in the composite is decisive. For symmetrical laminates, the plane of symmetry is recommended as the reference layer; for asymmetrical laminates, it can be freely selected.
